apiVersion: v1
kind: Pod
metadata:
 name: sfr-pod-nazneen-rajani
 namespace: sfr-ns-nazneen-rajani
spec:
  restartPolicy: OnFailure
  volumes:
    - name: sfr-home-pv-nazneen-rajani
      persistentVolumeClaim:
        claimName: sfr-home-pvc-nazneen-rajani
    - name: sfr-share-pv-nazneen-rajani
      persistentVolumeClaim:
        claimName: sfr-share-pvc-nazneen-rajani
  containers:
    - name: nazneen-rajani-scratchpad
      image: "gcr.io/salesforce-research-internal/hguo-scratchpad:IMAGE_TAG"
      command: ["/bin/bash"]
      args: ["-c", "cd hguo-scratchpad/ && bash ./scripts/run_experiments.sh"]
      resources:
        limits:
          nvidia.com/gpu: 1
          cpu: "7"
          memory: 45G
      volumeMounts:
        - name: sfr-home-pv-nazneen-rajani
          mountPath: "/export/home"
        - name: sfr-share-pv-nazneen-rajani
          mountPath: "/export/share"
  tolerations:
  - key: "gpu_num"
    operator: "Equal"
    value: "2"
    effect: "NoSchedule"